version: '2'
services:
    mysql:
        image: concord11s/flexon_project:part1
        ports:
            - "3306:3306"
        environment: 
            - MYSQL_ROOT_PASSWORD=supersecret

    java:
        image: concord11s/flexon_project:part2
        ports:
            - "3333:8080"
        depends_on:
            - mysql
